### ISSUE TITLE
Package release / access

### ISSUE THREAD

**Issue by wxmerkt** [ros2-gbp/apriltag-release#1]
Hi,
I've just prepared releases of a new AprilTag release for Melodic, Noetic, and Foxy -- these are all using the original release repository AprilRobotics/apriltag-release. Since Rolling and Galactic are released using this repository, I cannot prepare a release. Will this happen automatically or would I need to be added to this repository in order to release Galactic/Rolling?

Many thanks,
Wolfgang

**Comment by nuclearsandwich** [comment]
Hi Wolfgang, to support the Rolling release scripts we are centralizing the ROS 2 release repositories in this organization.

I [just announced](https://discourse.ros.org/t/upcoming-changes-to-ros2-gbp-organization/21878) some upcoming changes to the ros2-gbp permissions model. When that change goes into effect tomorrow, you and @mkrogius will receive invitations to join this organization and a team with maintenance access to this repository.

For the other ROS distributions, you'll have the choice of either continuing to use the original release repository in the AprilRobotics organization, or I can help migrate the content from the AprilRobotics release repository into the ros2-gbp one and you transition to using this one release repository for all releases, or split between ROS 1 (Melodic and Noetic) releases in AprilRobotics and ROS 2 (Foxy, Galactic, Rolling, and on) in ros2-gbp.

**Comment by wxmerkt** [comment]
Hi Steven!
Thank you very much for the swift update and detailed announcement. I'll wait for the invite and use this repository for ROS2 releases going forward.

Many thanks,
Wolfgang

**Comment by nuclearsandwich** [comment]
Invitations have been dispatched. When you accept the invitation could you please close this issue after you have confirmed your access.

**Comment by wxmerkt** [comment]
Thank you very much - it's working.
