### ISSUE TITLE
How to get release of humble distro? 

### ISSUE THREAD

**Issue by jeremy-ssg** [ros2-gbp/apriltag-release#4]
Great job! I can't find a release version for humble rosdistro. Could you please tell me how to use in humble rosdistro? Thank you very much!

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
